# Generated by Django 4.1.3 on 2022-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo_photo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=3)),
                ('resident', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
