# Generated by Django 4.1.3 on 2022-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtitle',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
