# Generated by Django 4.1.3 on 2022-12-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_dare_blogtitle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtitle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
