# Generated by Django 4.1.3 on 2022-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_blogtitle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtitle',
            name='date',
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
